CLI: Add Mac OS support for all subcommands except 'run'
subtrace/subtrace pull request #95
Opened 2024-12-31 02:50 UTC by sachin9996

2024-12-31 02:53 UTC, sachin9996 commented on subtrace.go
> +	if runtime.GOOS == "linux" {
Not sure if the more idiomatic way would be to put this logic in a separate file so we can use a build tag instead of an `if` condition

2025-01-01 17:05 UTC, adtac requested changes
also lowercase commit message with a different prefix please :) maybe `go: add macos support`?

2025-01-01 17:05 UTC, adtac commented on subtrace.go
> +	if runtime.GOOS == "linux" {
This PR is mostly good, but one thing I'd change is to create two files `subtrace_linux.go` and `subtrace_darwin.go` with just a `var subcommands = []*ffcli.Command{foo.NewCommand(), ...}` in each of them. The list would be different for each OS. Then `subtrace.go` can just do `c.Subcommands = subcommands`.

This way, building subtrace on macos will simply not depend on `subtrace.dev/cmd/run`. So none of the file renames in `cmd/run` would be needed; that package would just never be referenced on a macos build, so the compiler wouldn't complain.

On linux, things would exactly the same way.

2025-01-01 17:55 UTC, adtac approved these changes

2025-01-01 17:57 UTC, merged